### ISSUE TITLE
Problem with a NaN value during training step

### ISSUE THREAD

**Issue by josanabr** [prsdm/ml-project#1]
Hello,

I just cloned the repository and encountered an issue that's related to the data rather than the code. Below is the error message I received:

```
root@1a7718acf551:/work/mlops-project# python3 main.py                                                                                                        
2024-09-26 20:36:07,235:INFO:Data ingestion completed successfully                                                                                            
2024-09-26 20:36:07,498:INFO:Data cleaning completed successfully                                                                                             
/usr/local/lib/python3.10/site-packages/sklearn/utils/_array_api.py:390: RuntimeWarning: invalid value encountered in cast                                    
  return x.astype(dtype, copy=copy, casting=casting)                                                                                                          
Traceback (most recent call last):                                                                                                                            
  File "/work/mlops-project/main.py", line 109, in <module>                                                                                                   
    train_with_mlflow()                                                                                                                                       
  File "/work/mlops-project/main.py", line 69, in train_with_mlflow                                                                                           
    trainer.train_model(X_train, y_train)                                                                                                                     
  File "/work/mlops-project/steps/train.py", line 55, in train_model                                                                                          
    self.pipeline.fit(X_train, y_train)                                                                                                                       
  File "/usr/local/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper                                                                       
    return fit_method(estimator, *args, **kwargs)                                                                                                             
  File "/usr/local/lib/python3.10/site-packages/imblearn/pipeline.py", line 329, in fit                                                                       
    Xt, yt = self._fit(X, y, routed_params)                                                                                                                   
  File "/usr/local/lib/python3.10/site-packages/imblearn/pipeline.py", line 265, in _fit                                                                      
    X, y, fitted_transformer = fit_resample_one_cached(                                                                                                       
  File "/usr/local/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__                                                                      
    return self.func(*args, **kwargs)                                                                                                                         
  File "/usr/local/lib/python3.10/site-packages/imblearn/pipeline.py", line 1057, in _fit_resample_one                                                        
    X_res, y_res = sampler.fit_resample(X, y, **params.get("fit_resample", {}))                                                                               
  File "/usr/local/lib/python3.10/site-packages/imblearn/base.py", line 208, in fit_resample                                                                  
    return super().fit_resample(X, y)                                                                                                                         
  File "/usr/local/lib/python3.10/site-packages/imblearn/base.py", line 104, in fit_resample                                                                  
    check_classification_targets(y)                                                                                                                           
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/multiclass.py", line 211, in check_classification_targets                                       
    y_type = type_of_target(y, input_name="y")                                                                                                                
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/multiclass.py", line 398, in type_of_target                                                     
    _assert_all_finite(data, input_name=input_name)                                                                                                           
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input y contains NaN.
``` 
I reviewed the code in steps/clean.py and noticed that certain fields are handled, but I suspect that a specific field in the CSV file might have been overlooked, which could explain the error mentioned above.

Thanks for your help,

**Comment by josanabr** [comment]
I just modified the `steps/clean.py` adding `data = data.dropna()` before to the `return data` sentence in `clean_data` function.

**Comment by josanabr** [comment]
I just modified the `steps/clean.py` file adding `data = data.dropna()` before to the `return data` sentence in `clean_data` function.

**Comment by prsdm** [comment]
I just ran it to double-check, and it's working fine on my end. Could you share more details so I can help you with any problems you might be facing?
![error](https://github.com/user-attachments/assets/9f24c79e-e5cf-4247-85ff-07d6fa4b78aa)
